name: Testing

'on':
  pull_request:
  push:
    branches: [ '*' ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        make venv
        make install-deps

    - name: Run py.test
      run: |
        make pytest
